name: Build
on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Use GoLang '^1.19'
              uses: actions/setup-go@v3
              with:
                  go-version: "^1.19"
                  cache: true
                  cache-dependency-path: go.sum

            - name: Build Binary
              run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-s -w' -o godo-ddns

            - name: Upload build
              if: github.ref_name == 'master'
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: godo-ddns
                  if-no-files-found: error
                  retention-days: 1

    publish:
        if: github.ref_name == 'master'
        needs: deploy
        runs-on: [ubuntu-latest]
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Download build
              uses: actions/download-artifact@v3
              with:
                  name: build

            - name: Build and Publish Docker image to GitHub Packages
              uses: VaultVulp/gp-docker-action@1.6.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  image-name: godo-ddns
                  dockerfile: Dockerfile

            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v2.2.1

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              id: build-and-push
              uses: docker/build-push-action@v3.2.0
              with:
                  context: .
                  push: true
                  tags: numero33/godo-ddns:latest
